spring:
  application:
    name: mall-nacos-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos服务注册中心地址
      config:
        server-addr: localhost:8848 #Nacos作为配置中心地址
        file-extension:  #指定yaml格式的配置
        namespace: public
        group:
mall:
  gateway:
    #网关动态路由
    dynamicRoute:
      enabled: true