server:
  port: 8001
spring:
  application:
    name: mall-registry
eureka:
  instance:
    hostname: localhost
  client:
    #Erueka是为注册中心，不需要检索服务信息;(表示是否从Eureka Server获取注册信息，默认为true。 如果这是一个单点的 Eureka Server，不需要同步其他节点的数据，可以设为false)
    fetch-registry: false
    #Eureka是为注册中心,是否需要将自己注册到注册中心上(默认为true),本次位单机部署,不需要设置为true;但是注册中心集群时候必须为true;因为集群时，其他Eureka需要从此Eureka中的节点上获取数据；
    register-with-eureka: false
  server:
    enable-self-preservation: false
