spring:
  datasource:
    url: jdbc:mysql://182.92.106.235:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: yanli521
  data:
    elasticsearch:
      cluster-nodes: 182.92.106.235:9300
      cluster-name: elasticsearch
  elasticsearch:
    rest:
      uris: ["http://182.92.106.235:9200"]
logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.macro.mall: debug